name: sunBlog deploy github action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: '21'
      - run: yarn install
      - run: yarn deploy
