name: sunBlog deploy github action
strategy:
  matrix:
    node-version: ['21.x']

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - run: yarn install
      - run: yarn deploy
